import { PrismaClient, DSAPhase, DSAProblemDifficulty } from "@prisma/client";

const prisma = new PrismaClient();

const patterns = [
  // PHASE 1: FOUNDATIONS
  {
    slug: "arrays",
    name: "Arrays",
    description: "Master array manipulation, traversal, and operations. Foundation for all DSA.",
    phase: DSAPhase.FOUNDATIONS,
    order: 1,
    icon: "LayoutGrid",
    color: "#3b82f6",
    recognitionSignals: JSON.stringify(["contiguous memory", "indexed access", "iteration needed", "subarray"]),
    whenToUse: "When you need O(1) access by index, contiguous memory, or iteration over elements",
    whenNotToUse: "When you need frequent insertions/deletions in the middle",
    realLifeAnalogy: "Like a row of mailboxes - each has a number and you can access any directly",
    commonMistakes: JSON.stringify(["Off-by-one errors", "Not handling empty arrays", "Modifying array while iterating"]),
  },
  {
    slug: "strings",
    name: "Strings",
    description: "String manipulation, pattern matching, and character operations.",
    phase: DSAPhase.FOUNDATIONS,
    order: 2,
    icon: "Type",
    color: "#8b5cf6",
    recognitionSignals: JSON.stringify(["character manipulation", "palindrome", "anagram", "substring"]),
    whenToUse: "When working with text, characters, or string patterns",
    whenNotToUse: "When you need numeric operations on characters without conversion",
    realLifeAnalogy: "Like a sentence made of letter blocks you can rearrange",
    commonMistakes: JSON.stringify(["Forgetting string immutability", "Case sensitivity", "Unicode handling"]),
  },
  {
    slug: "complexity-analysis",
    name: "Complexity Analysis",
    description: "Big O notation, time/space complexity, and algorithm analysis.",
    phase: DSAPhase.FOUNDATIONS,
    order: 3,
    icon: "BarChart3",
    color: "#06b6d4",
    recognitionSignals: JSON.stringify(["optimize", "efficiency", "scale", "performance"]),
    whenToUse: "Always - to choose the right algorithm for the problem",
    whenNotToUse: "Never skip this - it is fundamental to all problem solving",
    realLifeAnalogy: "Like estimating travel time - knowing if you should walk, drive, or fly",
    commonMistakes: JSON.stringify(["Confusing O(n) with O(n^2)", "Ignoring space complexity", "Missing constant factors"]),
  },
  {
    slug: "math",
    name: "Math and Number Theory",
    description: "GCD, prime numbers, modular arithmetic, and mathematical tricks.",
    phase: DSAPhase.FOUNDATIONS,
    order: 4,
    icon: "Calculator",
    color: "#10b981",
    recognitionSignals: JSON.stringify(["divisible", "prime", "factor", "modulo", "mathematical property"]),
    whenToUse: "When the problem involves mathematical properties or optimizations",
    whenNotToUse: "When pure data structure manipulation is sufficient",
    realLifeAnalogy: "Like knowing shortcuts in arithmetic to solve problems faster",
    commonMistakes: JSON.stringify(["Integer overflow", "Division by zero", "Incorrect modulo operations"]),
  },
  // PHASE 2: LINEAR PATTERNS
  {
    slug: "hashing",
    name: "Hashing",
    description: "Hash maps, hash sets, and frequency counting for O(1) lookups.",
    phase: DSAPhase.LINEAR_PATTERNS,
    order: 5,
    icon: "Hash",
    color: "#f59e0b",
    recognitionSignals: JSON.stringify(["frequency", "count", "lookup", "duplicate", "two sum"]),
    whenToUse: "When you need O(1) average lookup, frequency counting, or grouping",
    whenNotToUse: "When memory is very limited or you need ordered data",
    realLifeAnalogy: "Like a phone book - look up name, get number instantly",
    commonMistakes: JSON.stringify(["Hash collision handling", "Not handling null keys", "Using wrong hash function"]),
  },
  {
    slug: "prefix-sum",
    name: "Prefix Sum",
    description: "Precompute cumulative sums for efficient range queries.",
    phase: DSAPhase.LINEAR_PATTERNS,
    order: 6,
    icon: "Plus",
    color: "#ec4899",
    recognitionSignals: JSON.stringify(["range sum", "subarray sum", "cumulative", "continuous"]),
    whenToUse: "When you need repeated range sum queries or subarray sums",
    whenNotToUse: "When the array changes frequently (use segment tree instead)",
    realLifeAnalogy: "Like knowing your bank balance at any date by subtracting two statements",
    commonMistakes: JSON.stringify(["Off-by-one in prefix array", "Not handling index 0", "Confusing with suffix sum"]),
  },
  {
    slug: "two-pointers",
    name: "Two Pointers",
    description: "Use two pointers to traverse arrays efficiently from different positions.",
    phase: DSAPhase.LINEAR_PATTERNS,
    order: 7,
    icon: "MoveHorizontal",
    color: "#14b8a6",
    recognitionSignals: JSON.stringify(["sorted array", "pair", "opposite ends", "merge", "compare"]),
    whenToUse: "When dealing with sorted arrays, pairs, or needing to compare elements from two ends",
    whenNotToUse: "When the data is not sorted and cannot be sorted",
    realLifeAnalogy: "Like two people walking towards each other from opposite ends of a hallway",
    commonMistakes: JSON.stringify(["Not moving both pointers correctly", "Infinite loops", "Missing edge cases"]),
  },
  {
    slug: "sliding-window",
    name: "Sliding Window",
    description: "Maintain a window over data for subarray/substring problems.",
    phase: DSAPhase.LINEAR_PATTERNS,
    order: 8,
    icon: "Frame",
    color: "#6366f1",
    recognitionSignals: JSON.stringify(["subarray", "substring", "contiguous", "window size", "max/min in window"]),
    whenToUse: "When you need to find contiguous subarray/substring with specific properties",
    whenNotToUse: "When elements can be non-contiguous (use other patterns)",
    realLifeAnalogy: "Like sliding a magnifying glass across a line of text to find a word",
    commonMistakes: JSON.stringify(["Incorrect window expansion/contraction", "Not resetting window", "Off-by-one errors"]),
  },
  // PHASE 3: SEARCHING
  {
    slug: "binary-search",
    name: "Binary Search",
    description: "Efficient O(log n) search on sorted data or answer spaces.",
    phase: DSAPhase.SEARCHING,
    order: 9,
    icon: "Search",
    color: "#ef4444",
    recognitionSignals: JSON.stringify(["sorted", "search", "O(log n)", "minimize max", "maximize min"]),
    whenToUse: "When data is sorted or you can define a monotonic search space",
    whenNotToUse: "When data is unsorted and cannot be sorted efficiently",
    realLifeAnalogy: "Like guessing a number by always halving the range",
    commonMistakes: JSON.stringify(["Infinite loops from incorrect mid calculation", "Wrong boundary updates", "Not handling single element"]),
  },
  {
    slug: "sorting",
    name: "Sorting Algorithms",
    description: "Quick sort, merge sort, and custom comparators.",
    phase: DSAPhase.SEARCHING,
    order: 10,
    icon: "ArrowUpDown",
    color: "#f97316",
    recognitionSignals: JSON.stringify(["sorted order", "custom comparator", "kth element", "partition"]),
    whenToUse: "When you need ordered data or custom ordering",
    whenNotToUse: "When O(n) solutions exist without sorting",
    realLifeAnalogy: "Like organizing books by height, then author, then title",
    commonMistakes: JSON.stringify(["Stable vs unstable sort confusion", "Stack overflow in quicksort", "Custom comparator errors"]),
  },
  {
    slug: "heap",
    name: "Heap / Priority Queue",
    description: "Min/max heap for efficient priority-based operations.",
    phase: DSAPhase.SEARCHING,
    order: 11,
    icon: "Triangle",
    color: "#a855f7",
    recognitionSignals: JSON.stringify(["top k", "median", "priority", "min/max element", "stream"]),
    whenToUse: "When you need quick access to min/max element or top K elements",
    whenNotToUse: "When you need random access or sorted iteration",
    realLifeAnalogy: "Like a hospital waiting room where most critical patients are seen first",
    commonMistakes: JSON.stringify(["Max heap vs min heap confusion", "Incorrect heapify", "Not handling empty heap"]),
  },
  // PHASE 4: HIERARCHICAL
  {
    slug: "linked-list",
    name: "Linked List",
    description: "Singly/doubly linked lists, cycle detection, and pointer manipulation.",
    phase: DSAPhase.HIERARCHICAL,
    order: 12,
    icon: "Link",
    color: "#0ea5e9",
    recognitionSignals: JSON.stringify(["pointer", "node", "cycle", "reverse", "merge lists"]),
    whenToUse: "When you need frequent insertions/deletions or cycle detection",
    whenNotToUse: "When you need random access by index",
    realLifeAnalogy: "Like a treasure hunt where each clue points to the next location",
    commonMistakes: JSON.stringify(["Losing reference to nodes", "Cycle creation", "Null pointer dereference"]),
  },
  {
    slug: "stack",
    name: "Stack",
    description: "LIFO data structure for balancing, nesting, and undo operations.",
    phase: DSAPhase.HIERARCHICAL,
    order: 13,
    icon: "Layers",
    color: "#d946ef",
    recognitionSignals: JSON.stringify(["balanced", "nested", "undo", "monotonic", "next greater"]),
    whenToUse: "When you need LIFO behavior, balanced parentheses, or monotonic operations",
    whenNotToUse: "When you need FIFO behavior (use queue)",
    realLifeAnalogy: "Like a stack of plates - you can only add or remove from the top",
    commonMistakes: JSON.stringify(["Stack overflow", "Not popping correctly", "Missing empty stack check"]),
  },
  {
    slug: "queue",
    name: "Queue and Deque",
    description: "FIFO data structure and double-ended queue operations.",
    phase: DSAPhase.HIERARCHICAL,
    order: 14,
    icon: "AlignJustify",
    color: "#84cc16",
    recognitionSignals: JSON.stringify(["FIFO", "BFS", "sliding window max", "first in first out"]),
    whenToUse: "When you need FIFO processing or sliding window maximum",
    whenNotToUse: "When you need LIFO behavior (use stack)",
    realLifeAnalogy: "Like a line at a coffee shop - first person in line gets served first",
    commonMistakes: JSON.stringify(["Queue vs deque confusion", "Not handling empty queue", "Incorrect dequeue"]),
  },
  {
    slug: "tree",
    name: "Binary Tree",
    description: "Tree traversals, construction, and path problems.",
    phase: DSAPhase.HIERARCHICAL,
    order: 15,
    icon: "GitBranch",
    color: "#22c55e",
    recognitionSignals: JSON.stringify(["tree", "binary", "traversal", "path", "depth", "height"]),
    whenToUse: "When dealing with hierarchical data or recursive structures",
    whenNotToUse: "When data is linear (use arrays/lists)",
    realLifeAnalogy: "Like a family tree - each person has at most two children",
    commonMistakes: JSON.stringify(["Missing base case in recursion", "Not handling null nodes", "Infinite recursion"]),
  },
  {
    slug: "bst",
    name: "Binary Search Tree",
    description: "BST properties, operations, and balanced trees.",
    phase: DSAPhase.HIERARCHICAL,
    order: 16,
    icon: "TreePine",
    color: "#16a34a",
    recognitionSignals: JSON.stringify(["sorted", "BST", "inorder", "balanced", "range query"]),
    whenToUse: "When you need sorted data with O(log n) operations",
    whenNotToUse: "When the tree becomes unbalanced (use AVL/Red-Black)",
    realLifeAnalogy: "Like a library organized by ISBN - you can quickly find any book",
    commonMistakes: JSON.stringify(["Not maintaining BST property", "Incorrect deletion logic", "Not handling duplicates"]),
  },
  {
    slug: "dfs",
    name: "DFS (Depth-First Search)",
    description: "Recursive/iterative depth-first traversal for trees and graphs.",
    phase: DSAPhase.HIERARCHICAL,
    order: 17,
    icon: "ArrowDown",
    color: "#0891b2",
    recognitionSignals: JSON.stringify(["path", "connected", "explore all", "backtrack", "recursion"]),
    whenToUse: "When you need to explore all paths, detect cycles, or solve maze-like problems",
    whenNotToUse: "When you need shortest path (use BFS)",
    realLifeAnalogy: "Like exploring a maze by always going as deep as possible before backtracking",
    commonMistakes: JSON.stringify(["Stack overflow in deep recursion", "Not marking visited nodes", "Missing backtracking step"]),
  },
  {
    slug: "bfs",
    name: "BFS (Breadth-First Search)",
    description: "Level-order traversal for shortest path in unweighted graphs.",
    phase: DSAPhase.HIERARCHICAL,
    order: 18,
    icon: "ArrowRight",
    color: "#0d9488",
    recognitionSignals: JSON.stringify(["shortest path", "level order", "unweighted", "minimum steps"]),
    whenToUse: "When you need shortest path in unweighted graphs or level-order processing",
    whenNotToUse: "When you need to explore all paths (use DFS)",
    realLifeAnalogy: "Like ripples in a pond - you explore outward one layer at a time",
    commonMistakes: JSON.stringify(["Using DFS instead", "Not tracking visited nodes", "Incorrect level counting"]),
  },
  // PHASE 5: ADVANCED
  {
    slug: "graph",
    name: "Graph Algorithms",
    description: "Graph representation, traversal, and fundamental algorithms.",
    phase: DSAPhase.ADVANCED,
    order: 19,
    icon: "Network",
    color: "#7c3aed",
    recognitionSignals: JSON.stringify(["graph", "node", "edge", "connected", "cycle", "component"]),
    whenToUse: "When the problem involves relationships between entities",
    whenNotToUse: "When data is hierarchical (use tree algorithms)",
    realLifeAnalogy: "Like a social network - people are nodes, friendships are edges",
    commonMistakes: JSON.stringify(["Directed vs undirected confusion", "Not handling disconnected components", "Cycle detection errors"]),
  },
  {
    slug: "backtracking",
    name: "Backtracking",
    description: "Systematic exploration with pruning for combinatorial problems.",
    phase: DSAPhase.ADVANCED,
    order: 20,
    icon: "RotateCcw",
    color: "#dc2626",
    recognitionSignals: JSON.stringify(["permutation", "combination", "N-Queen", "all solutions", "generate"]),
    whenToUse: "When you need to generate all valid configurations or find one valid configuration",
    whenNotToUse: "When greedy or DP provides a more efficient solution",
    realLifeAnalogy: "Like solving a Sudoku puzzle - try a number, if it does not work, undo and try another",
    commonMistakes: JSON.stringify(["Missing backtrack step", "Not pruning invalid paths", "Incorrect base case"]),
  },
  {
    slug: "trie",
    name: "Trie",
    description: "Prefix tree for efficient string operations and autocomplete.",
    phase: DSAPhase.ADVANCED,
    order: 21,
    icon: "Network",
    color: "#4f46e5",
    recognitionSignals: JSON.stringify(["prefix", "autocomplete", "dictionary", "word search"]),
    whenToUse: "When you need prefix-based operations or word-level processing",
    whenNotToUse: "When simple hash map suffices for exact matching",
    realLifeAnalogy: "Like a dictionary where you flip pages by first letter, then second, etc.",
    commonMistakes: JSON.stringify(["Not handling word endings correctly", "Memory inefficiency", "Incorrect prefix matching"]),
  },
  {
    slug: "union-find",
    name: "Union Find",
    description: "Disjoint set data structure for connected components.",
    phase: DSAPhase.ADVANCED,
    order: 22,
    icon: "Merge",
    color: "#be185d",
    recognitionSignals: JSON.stringify(["connected components", "merge", "union", "group", "disconnect"]),
    whenToUse: "When you need to efficiently merge sets and check connectivity",
    whenNotToUse: "When you need ordered operations on sets",
    realLifeAnalogy: "Like tracking which friend groups are connected at a party",
    commonMistakes: JSON.stringify(["Not using path compression", "Incorrect union by rank", "Not initializing properly"]),
  },
  {
    slug: "topological-sort",
    name: "Topological Sort",
    description: "Linear ordering of vertices in DAGs for dependency resolution.",
    phase: DSAPhase.ADVANCED,
    order: 23,
    icon: "ArrowDownUp",
    color: "#9333ea",
    recognitionSignals: JSON.stringify(["dependency", "ordering", "DAG", "course schedule", "prerequisite"]),
    whenToUse: "When you need to order tasks with dependencies or detect cycles",
    whenNotToUse: "When the graph has cycles (not a DAG)",
    realLifeAnalogy: "Like planning courses - you must take prerequisites before advanced classes",
    commonMistakes: JSON.stringify(["Not detecting cycles", "Incorrect DFS/BFS ordering", "Missing nodes with no dependencies"]),
  },
  {
    slug: "shortest-path",
    name: "Shortest Path Algorithms",
    description: "Dijkstra, Bellman-Ford, and Floyd-Warshall for weighted graphs.",
    phase: DSAPhase.ADVANCED,
    order: 24,
    icon: "Route",
    color: "#059669",
    recognitionSignals: JSON.stringify(["shortest", "minimum cost", "weighted", "distance", "network delay"]),
    whenToUse: "When you need shortest/cheapest path in weighted graphs",
    whenNotToUse: "When graph is unweighted (use BFS)",
    realLifeAnalogy: "Like GPS navigation finding the fastest route considering traffic",
    commonMistakes: JSON.stringify(["Negative weight handling", "Not using priority queue", "Incorrect relaxation"]),
  },
  {
    slug: "mst",
    name: "Minimum Spanning Tree",
    description: "Kruskal and Prim algorithms for minimum cost connectivity.",
    phase: DSAPhase.ADVANCED,
    order: 25,
    icon: "TreeDeciduous",
    color: "#b45309",
    recognitionSignals: JSON.stringify(["minimum cost", "connect all", "spanning", "wire", "network"]),
    whenToUse: "When you need to connect all nodes with minimum total edge weight",
    whenNotToUse: "When you need shortest paths (use shortest path algorithms)",
    realLifeAnalogy: "Like laying cable to connect all houses with minimum total wire length",
    commonMistakes: JSON.stringify(["Confusing MST with shortest path", "Incorrect edge sorting", "Not handling disconnected graphs"]),
  },
  // PHASE 6: OPTIMIZATION
  {
    slug: "greedy",
    name: "Greedy Algorithms",
    description: "Local optimal choices for global optimization.",
    phase: DSAPhase.OPTIMIZATION,
    order: 26,
    icon: "Zap",
    color: "#eab308",
    recognitionSignals: JSON.stringify(["maximum", "minimum", "optimal", "interval", "scheduling"]),
    whenToUse: "When local optimal choices lead to global optimum (exchange argument provable)",
    whenNotToUse: "When greedy fails (use DP instead)",
    realLifeAnalogy: "Like always picking the highest paying job from available options",
    commonMistakes: JSON.stringify(["Incorrect greedy choice", "Not proving correctness", "Missing edge cases"]),
  },
  {
    slug: "dp",
    name: "Dynamic Programming",
    description: "Optimal substructure and overlapping subproblems for optimization.",
    phase: DSAPhase.OPTIMIZATION,
    order: 27,
    icon: "Database",
    color: "#2563eb",
    recognitionSignals: JSON.stringify(["optimize", "minimum/maximum", "count ways", "subsequence", "knapsack"]),
    whenToUse: "When problem has optimal substructure and overlapping subproblems",
    whenNotToUse: "When greedy works or when there are no overlapping subproblems",
    realLifeAnalogy: "Like breaking a big problem into smaller pieces and remembering solutions",
    commonMistakes: JSON.stringify(["Incorrect state definition", "Wrong transition", "Memory limit exceeded"]),
  },
  {
    slug: "bit-manipulation",
    name: "Bit Manipulation",
    description: "Bitwise operations for efficient low-level computations.",
    phase: DSAPhase.OPTIMIZATION,
    order: 28,
    icon: "Binary",
    color: "#64748b",
    recognitionSignals: JSON.stringify(["bit", "XOR", "mask", "power of 2", "single number"]),
    whenToUse: "When you need efficient bitwise operations or subset enumeration",
    whenNotToUse: "When standard operations are clearer and equally efficient",
    realLifeAnalogy: "Like light switches - each bit is on or off, and operations combine them",
    commonMistakes: JSON.stringify(["Operator precedence", "Signed vs unsigned", "Off-by-one in bit shifts"]),
  },
  {
    slug: "segment-tree",
    name: "Segment Tree",
    description: "Range queries and updates on arrays in O(log n).",
    phase: DSAPhase.OPTIMIZATION,
    order: 29,
    icon: "TreeDeciduous",
    color: "#0d9488",
    recognitionSignals: JSON.stringify(["range query", "range update", "interval", "segment"]),
    whenToUse: "When you need efficient range queries and point/range updates",
    whenNotToUse: "When simple prefix sum suffices or when data does not change",
    realLifeAnalogy: "Like a company org chart where each manager knows stats for their team",
    commonMistakes: JSON.stringify(["Incorrect build logic", "Lazy propagation errors", "Off-by-one in ranges"]),
  },
  {
    slug: "fenwick-tree",
    name: "Fenwick Tree (BIT)",
    description: "Binary Indexed Tree for prefix sums and updates.",
    phase: DSAPhase.OPTIMIZATION,
    order: 30,
    icon: "TreePine",
    color: "#7c3aed",
    recognitionSignals: JSON.stringify(["prefix sum", "point update", "frequency", "inversion count"]),
    whenToUse: "When you need efficient prefix sum queries with point updates",
    whenNotToUse: "When you need range updates (use segment tree)",
    realLifeAnalogy: "Like a running total that you can update efficiently",
    commonMistakes: JSON.stringify(["1-indexed vs 0-indexed confusion", "Incorrect lowbit calculation", "Update vs query confusion"]),
  },
];

const problems = [
  // ARRAYS - Tier 1
  { leetcodeId: 1, title: "Two Sum", slug: "two-sum", difficulty: "EASY" as const, patternSlug: "arrays", tier: 1, companies: ["Google", "Amazon", "Meta", "Microsoft"], tags: ["hashing", "two-pointers"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 26, title: "Remove Duplicates from Sorted Array", slug: "remove-duplicates-from-sorted-array", difficulty: "EASY" as const, patternSlug: "arrays", tier: 1, companies: ["Amazon", "Microsoft"], tags: ["two-pointers"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 27, title: "Remove Element", slug: "remove-element", difficulty: "EASY" as const, patternSlug: "arrays", tier: 1, companies: ["Amazon"], tags: ["two-pointers"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 35, title: "Search Insert Position", slug: "search-insert-position", difficulty: "EASY" as const, patternSlug: "arrays", tier: 1, companies: ["Microsoft"], tags: ["binary-search"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 53, title: "Maximum Subarray", slug: "maximum-subarray", difficulty: "MEDIUM" as const, patternSlug: "arrays", tier: 1, companies: ["Google", "Amazon", "Meta"], tags: ["dp", "divide-conquer"], expectedTime: 20, revisionFrequency: 7 },
  // ARRAYS - Tier 2
  { leetcodeId: 15, title: "3Sum", slug: "3sum", difficulty: "MEDIUM" as const, patternSlug: "arrays", tier: 2, companies: ["Amazon", "Meta", "Microsoft"], tags: ["two-pointers", "sorting"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 11, title: "Container With Most Water", slug: "container-with-most-water", difficulty: "MEDIUM" as const, patternSlug: "arrays", tier: 2, companies: ["Amazon", "Google"], tags: ["two-pointers"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 238, title: "Product of Array Except Self", slug: "product-of-array-except-self", difficulty: "MEDIUM" as const, patternSlug: "arrays", tier: 2, companies: ["Amazon", "Microsoft", "Meta"], tags: ["prefix-sum"], expectedTime: 15, revisionFrequency: 7 },
  // ARRAYS - Tier 4
  { leetcodeId: 42, title: "Trapping Rain Water", slug: "trapping-rain-water", difficulty: "HARD" as const, patternSlug: "arrays", tier: 4, companies: ["Google", "Amazon", "Goldman Sachs"], tags: ["two-pointers", "stack", "dp"], expectedTime: 35, revisionFrequency: 3 },
  // STRINGS
  { leetcodeId: 125, title: "Valid Palindrome", slug: "valid-palindrome", difficulty: "EASY" as const, patternSlug: "strings", tier: 1, companies: ["Amazon", "Microsoft"], tags: ["two-pointers"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 344, title: "Reverse String", slug: "reverse-string", difficulty: "EASY" as const, patternSlug: "strings", tier: 1, companies: ["Amazon"], tags: ["two-pointers"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 242, title: "Valid Anagram", slug: "valid-anagram", difficulty: "EASY" as const, patternSlug: "strings", tier: 1, companies: ["Amazon", "Google"], tags: ["hashing"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 3, title: "Longest Substring Without Repeating Characters", slug: "longest-substring-without-repeating-characters", difficulty: "MEDIUM" as const, patternSlug: "strings", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["sliding-window", "hashing"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 76, title: "Minimum Window Substring", slug: "minimum-window-substring", difficulty: "HARD" as const, patternSlug: "strings", tier: 4, companies: ["Meta", "Amazon", "Microsoft"], tags: ["sliding-window", "hashing"], expectedTime: 30, revisionFrequency: 3 },
  // HASHING
  { leetcodeId: 49, title: "Group Anagrams", slug: "group-anagrams", difficulty: "MEDIUM" as const, patternSlug: "hashing", tier: 2, companies: ["Amazon", "Google"], tags: ["hashing", "sorting"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 128, title: "Longest Consecutive Sequence", slug: "longest-consecutive-sequence", difficulty: "MEDIUM" as const, patternSlug: "hashing", tier: 2, companies: ["Google", "Amazon"], tags: ["hashing"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 380, title: "Insert Delete GetRandom O(1)", slug: "insert-delete-getrandom-o1", difficulty: "MEDIUM" as const, patternSlug: "hashing", tier: 3, companies: ["Google", "Amazon"], tags: ["hashing", "design"], expectedTime: 25, revisionFrequency: 7 },
  // TWO POINTERS
  { leetcodeId: 167, title: "Two Sum II", slug: "two-sum-ii-input-array-is-sorted", difficulty: "MEDIUM" as const, patternSlug: "two-pointers", tier: 1, companies: ["Amazon"], tags: ["two-pointers"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 977, title: "Squares of a Sorted Array", slug: "squares-of-a-sorted-array", difficulty: "EASY" as const, patternSlug: "two-pointers", tier: 1, companies: ["Amazon"], tags: ["two-pointers"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 142, title: "Linked List Cycle II", slug: "linked-list-cycle-ii", difficulty: "MEDIUM" as const, patternSlug: "two-pointers", tier: 2, companies: ["Amazon", "Microsoft"], tags: ["linked-list", "two-pointers"], expectedTime: 15, revisionFrequency: 7 },
  // SLIDING WINDOW
  { leetcodeId: 209, title: "Minimum Size Subarray Sum", slug: "minimum-size-subarray-sum", difficulty: "MEDIUM" as const, patternSlug: "sliding-window", tier: 2, companies: ["Amazon"], tags: ["sliding-window"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 438, title: "Find All Anagrams in a String", slug: "find-all-anagrams-in-a-string", difficulty: "MEDIUM" as const, patternSlug: "sliding-window", tier: 2, companies: ["Amazon", "Meta"], tags: ["sliding-window", "hashing"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 567, title: "Permutation in String", slug: "permutation-in-string", difficulty: "MEDIUM" as const, patternSlug: "sliding-window", tier: 2, companies: ["Microsoft"], tags: ["sliding-window"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 239, title: "Sliding Window Maximum", slug: "sliding-window-maximum", difficulty: "HARD" as const, patternSlug: "sliding-window", tier: 4, companies: ["Amazon", "Google", "Meta"], tags: ["sliding-window", "deque", "heap"], expectedTime: 30, revisionFrequency: 3 },
  // PREFIX SUM
  { leetcodeId: 303, title: "Range Sum Query - Immutable", slug: "range-sum-query-immutable", difficulty: "EASY" as const, patternSlug: "prefix-sum", tier: 1, companies: [], tags: ["prefix-sum", "design"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 560, title: "Subarray Sum Equals K", slug: "subarray-sum-equals-k", difficulty: "MEDIUM" as const, patternSlug: "prefix-sum", tier: 2, companies: ["Amazon", "Google"], tags: ["prefix-sum", "hashing"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 525, title: "Contiguous Array", slug: "contiguous-array", difficulty: "MEDIUM" as const, patternSlug: "prefix-sum", tier: 2, companies: ["Amazon"], tags: ["prefix-sum", "hashing"], expectedTime: 20, revisionFrequency: 7 },
  // BINARY SEARCH
  { leetcodeId: 704, title: "Binary Search", slug: "binary-search", difficulty: "EASY" as const, patternSlug: "binary-search", tier: 1, companies: [], tags: ["binary-search"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 33, title: "Search in Rotated Sorted Array", slug: "search-in-rotated-sorted-array", difficulty: "MEDIUM" as const, patternSlug: "binary-search", tier: 2, companies: ["Amazon", "Microsoft"], tags: ["binary-search"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 34, title: "Find First and Last Position of Element in Sorted Array", slug: "find-first-and-last-position-of-element-in-sorted-array", difficulty: "MEDIUM" as const, patternSlug: "binary-search", tier: 2, companies: ["Amazon", "Google"], tags: ["binary-search"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 4, title: "Median of Two Sorted Arrays", slug: "median-of-two-sorted-arrays", difficulty: "HARD" as const, patternSlug: "binary-search", tier: 4, companies: ["Google", "Amazon", "Meta"], tags: ["binary-search"], expectedTime: 35, revisionFrequency: 3 },
  // STACK
  { leetcodeId: 20, title: "Valid Parentheses", slug: "valid-parentheses", difficulty: "EASY" as const, patternSlug: "stack", tier: 1, companies: ["Amazon", "Meta"], tags: ["stack"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 155, title: "Min Stack", slug: "min-stack", difficulty: "MEDIUM" as const, patternSlug: "stack", tier: 2, companies: ["Amazon"], tags: ["stack", "design"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 394, title: "Decode String", slug: "decode-string", difficulty: "MEDIUM" as const, patternSlug: "stack", tier: 2, companies: ["Amazon", "Google"], tags: ["stack", "recursion"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 84, title: "Largest Rectangle in Histogram", slug: "largest-rectangle-in-histogram", difficulty: "HARD" as const, patternSlug: "stack", tier: 4, companies: ["Google", "Amazon"], tags: ["stack", "monotonic-stack"], expectedTime: 30, revisionFrequency: 3 },
  // LINKED LIST
  { leetcodeId: 206, title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "EASY" as const, patternSlug: "linked-list", tier: 1, companies: ["Amazon", "Microsoft"], tags: ["linked-list"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 21, title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "EASY" as const, patternSlug: "linked-list", tier: 1, companies: ["Amazon", "Microsoft"], tags: ["linked-list"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 19, title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "MEDIUM" as const, patternSlug: "linked-list", tier: 2, companies: ["Amazon", "Meta"], tags: ["linked-list", "two-pointers"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 23, title: "Merge k Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "HARD" as const, patternSlug: "linked-list", tier: 4, companies: ["Amazon", "Google", "Meta"], tags: ["linked-list", "heap", "divide-conquer"], expectedTime: 30, revisionFrequency: 3 },
  // TREE
  { leetcodeId: 104, title: "Maximum Depth of Binary Tree", slug: "maximum-depth-of-binary-tree", difficulty: "EASY" as const, patternSlug: "tree", tier: 1, companies: ["Amazon"], tags: ["tree", "dfs"], expectedTime: 10, revisionFrequency: 14 },
  { leetcodeId: 102, title: "Binary Tree Level Order Traversal", slug: "binary-tree-level-order-traversal", difficulty: "MEDIUM" as const, patternSlug: "tree", tier: 2, companies: ["Amazon", "Meta"], tags: ["tree", "bfs"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 236, title: "Lowest Common Ancestor of a Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree", difficulty: "MEDIUM" as const, patternSlug: "tree", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["tree", "dfs"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 124, title: "Binary Tree Maximum Path Sum", slug: "binary-tree-maximum-path-sum", difficulty: "HARD" as const, patternSlug: "tree", tier: 4, companies: ["Google", "Meta"], tags: ["tree", "dfs"], expectedTime: 30, revisionFrequency: 3 },
  // BST
  { leetcodeId: 98, title: "Validate Binary Search Tree", slug: "validate-binary-search-tree", difficulty: "MEDIUM" as const, patternSlug: "bst", tier: 2, companies: ["Amazon", "Google"], tags: ["bst", "dfs"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 230, title: "Kth Smallest Element in a BST", slug: "kth-smallest-element-in-a-bst", difficulty: "MEDIUM" as const, patternSlug: "bst", tier: 2, companies: ["Amazon"], tags: ["bst", "dfs"], expectedTime: 15, revisionFrequency: 7 },
  // GRAPH
  { leetcodeId: 200, title: "Number of Islands", slug: "number-of-islands", difficulty: "MEDIUM" as const, patternSlug: "graph", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["graph", "dfs", "bfs"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 133, title: "Clone Graph", slug: "clone-graph", difficulty: "MEDIUM" as const, patternSlug: "graph", tier: 2, companies: ["Amazon", "Meta"], tags: ["graph", "dfs", "hashing"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 417, title: "Pacific Atlantic Water Flow", slug: "pacific-atlantic-water-flow", difficulty: "MEDIUM" as const, patternSlug: "graph", tier: 3, companies: ["Amazon", "Google"], tags: ["graph", "dfs", "bfs"], expectedTime: 30, revisionFrequency: 7 },
  // BACKTRACKING
  { leetcodeId: 46, title: "Permutations", slug: "permutations", difficulty: "MEDIUM" as const, patternSlug: "backtracking", tier: 2, companies: ["Amazon", "Meta"], tags: ["backtracking"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 78, title: "Subsets", slug: "subsets", difficulty: "MEDIUM" as const, patternSlug: "backtracking", tier: 2, companies: ["Amazon", "Google"], tags: ["backtracking", "bit-manipulation"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 51, title: "N-Queens", slug: "n-queens", difficulty: "HARD" as const, patternSlug: "backtracking", tier: 4, companies: ["Amazon", "Google", "Meta"], tags: ["backtracking"], expectedTime: 30, revisionFrequency: 3 },
  // TRIE
  { leetcodeId: 208, title: "Implement Trie", slug: "implement-trie-prefix-tree", difficulty: "MEDIUM" as const, patternSlug: "trie", tier: 2, companies: ["Amazon", "Google"], tags: ["trie", "design"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 211, title: "Design Add and Search Words Data Structure", slug: "design-add-and-search-words-data-structure", difficulty: "MEDIUM" as const, patternSlug: "trie", tier: 3, companies: ["Amazon", "Meta"], tags: ["trie", "dfs", "design"], expectedTime: 25, revisionFrequency: 7 },
  // UNION FIND
  { leetcodeId: 547, title: "Number of Provinces", slug: "number-of-provinces", difficulty: "MEDIUM" as const, patternSlug: "union-find", tier: 2, companies: ["Amazon", "Google"], tags: ["union-find", "graph"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 684, title: "Redundant Connection", slug: "redundant-connection", difficulty: "MEDIUM" as const, patternSlug: "union-find", tier: 2, companies: ["Amazon"], tags: ["union-find", "graph"], expectedTime: 20, revisionFrequency: 7 },
  // TOPOLOGICAL SORT
  { leetcodeId: 207, title: "Course Schedule", slug: "course-schedule", difficulty: "MEDIUM" as const, patternSlug: "topological-sort", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["topological-sort", "graph", "dfs", "bfs"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 210, title: "Course Schedule II", slug: "course-schedule-ii", difficulty: "MEDIUM" as const, patternSlug: "topological-sort", tier: 2, companies: ["Amazon", "Google"], tags: ["topological-sort", "graph"], expectedTime: 25, revisionFrequency: 7 },
  // SHORTEST PATH
  { leetcodeId: 743, title: "Network Delay Time", slug: "network-delay-time", difficulty: "MEDIUM" as const, patternSlug: "shortest-path", tier: 2, companies: ["Amazon", "Google"], tags: ["shortest-path", "graph", "heap"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 787, title: "Cheapest Flights Within K Stops", slug: "cheapest-flights-within-k-stops", difficulty: "MEDIUM" as const, patternSlug: "shortest-path", tier: 3, companies: ["Amazon", "Google"], tags: ["shortest-path", "graph", "dp"], expectedTime: 30, revisionFrequency: 7 },
  // GREEDY
  { leetcodeId: 55, title: "Jump Game", slug: "jump-game", difficulty: "MEDIUM" as const, patternSlug: "greedy", tier: 2, companies: ["Amazon", "Google"], tags: ["greedy", "dp"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 45, title: "Jump Game II", slug: "jump-game-ii", difficulty: "MEDIUM" as const, patternSlug: "greedy", tier: 2, companies: ["Amazon", "Google"], tags: ["greedy", "dp"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 763, title: "Partition Labels", slug: "partition-labels", difficulty: "MEDIUM" as const, patternSlug: "greedy", tier: 2, companies: ["Amazon"], tags: ["greedy"], expectedTime: 15, revisionFrequency: 7 },
  // DP
  { leetcodeId: 70, title: "Climbing Stairs", slug: "climbing-stairs", difficulty: "EASY" as const, patternSlug: "dp", tier: 1, companies: ["Amazon"], tags: ["dp"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 198, title: "House Robber", slug: "house-robber", difficulty: "MEDIUM" as const, patternSlug: "dp", tier: 2, companies: ["Amazon", "Google"], tags: ["dp"], expectedTime: 15, revisionFrequency: 7 },
  { leetcodeId: 322, title: "Coin Change", slug: "coin-change", difficulty: "MEDIUM" as const, patternSlug: "dp", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["dp"], expectedTime: 20, revisionFrequency: 7 },
  { leetcodeId: 300, title: "Longest Increasing Subsequence", slug: "longest-increasing-subsequence", difficulty: "MEDIUM" as const, patternSlug: "dp", tier: 2, companies: ["Amazon", "Google", "Meta"], tags: ["dp", "binary-search"], expectedTime: 25, revisionFrequency: 7 },
  { leetcodeId: 312, title: "Burst Balloons", slug: "burst-balloons", difficulty: "HARD" as const, patternSlug: "dp", tier: 4, companies: ["Google", "Amazon"], tags: ["dp"], expectedTime: 35, revisionFrequency: 3 },
  // BIT MANIPULATION
  { leetcodeId: 136, title: "Single Number", slug: "single-number", difficulty: "EASY" as const, patternSlug: "bit-manipulation", tier: 1, companies: ["Amazon"], tags: ["bit-manipulation"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 191, title: "Number of 1 Bits", slug: "number-of-1-bits", difficulty: "EASY" as const, patternSlug: "bit-manipulation", tier: 1, companies: ["Amazon"], tags: ["bit-manipulation"], expectedTime: 10, revisionFrequency: 7 },
  { leetcodeId: 338, title: "Counting Bits", slug: "counting-bits", difficulty: "EASY" as const, patternSlug: "bit-manipulation", tier: 2, companies: ["Amazon"], tags: ["bit-manipulation", "dp"], expectedTime: 15, revisionFrequency: 7 },
];

const companyTracks = [
  { slug: "google", name: "Google", description: "Top DSA problems asked at Google interviews", problemCount: 45, avgDifficulty: "Medium-Hard", strategy: "Focus on graphs, trees, DP, and system design. Google values clean code and optimal solutions." },
  { slug: "amazon", name: "Amazon", description: "Most frequently asked DSA problems at Amazon", problemCount: 50, avgDifficulty: "Medium", strategy: "Heavy on arrays, strings, trees, and graphs. Leadership principles integration in technical questions." },
  { slug: "microsoft", name: "Microsoft", description: "Microsoft interview DSA problem collection", problemCount: 40, avgDifficulty: "Medium", strategy: "Strong focus on linked lists, trees, BST, and DP. Clean code matters." },
  { slug: "meta", name: "Meta", description: "Meta (Facebook) DSA interview preparation", problemCount: 42, avgDifficulty: "Medium-Hard", strategy: "Graph algorithms, trees, arrays, and system design. Speed and accuracy both matter." },
  { slug: "apple", name: "Apple", description: "Apple interview DSA questions", problemCount: 35, avgDifficulty: "Medium", strategy: "Arrays, strings, linked lists, and trees. Apple values clean, readable code." },
  { slug: "netflix", name: "Netflix", description: "Netflix engineering interview problems", problemCount: 30, avgDifficulty: "Hard", strategy: "Advanced algorithms, system design, and real-world problem solving." },
  { slug: "uber", name: "Uber", description: "Uber interview DSA preparation", problemCount: 35, avgDifficulty: "Medium", strategy: "Graphs, strings, DP, and design problems. Real-time systems focus." },
  { slug: "adobe", name: "Adobe", description: "Adobe interview DSA problems", problemCount: 30, avgDifficulty: "Medium", strategy: "Arrays, trees, DP, and creative problem solving." },
  { slug: "flipkart", name: "Flipkart", description: "Flipkart DSA interview preparation", problemCount: 35, avgDifficulty: "Medium", strategy: "E-commerce focused problems: arrays, trees, graphs, DP." },
  { slug: "atlassian", name: "Atlassian", description: "Atlassian interview DSA questions", problemCount: 30, avgDifficulty: "Medium", strategy: "Trees, graphs, arrays, and collaborative problem solving." },
];

async function main() {
  console.log("Seeding DSA Mastery Hub...");

  // Upsert patterns
  for (const pattern of patterns) {
    await prisma.dSAPattern.upsert({
      where: { slug: pattern.slug },
      update: pattern,
      create: pattern,
    });
  }
  console.log(`Seeded ${patterns.length} patterns`);

  // Upsert problems
  for (const problem of problems) {
    const pattern = await prisma.dSAPattern.findUnique({ where: { slug: problem.patternSlug } });
    await prisma.dSAProblem.upsert({
      where: { leetcodeId: problem.leetcodeId },
      update: {
        title: problem.title,
        slug: problem.slug,
        difficulty: problem.difficulty,
        patternId: pattern?.id || null,
        tier: problem.tier,
        companies: problem.companies,
        tags: problem.tags,
        expectedTime: problem.expectedTime,
        revisionFrequency: problem.revisionFrequency,
      },
      create: {
        leetcodeId: problem.leetcodeId,
        title: problem.title,
        slug: problem.slug,
        difficulty: problem.difficulty,
        patternId: pattern?.id || null,
        tier: problem.tier,
        companies: problem.companies,
        tags: problem.tags,
        expectedTime: problem.expectedTime,
        revisionFrequency: problem.revisionFrequency,
      },
    });
  }
  console.log(`Seeded ${problems.length} problems`);

  // Upsert company tracks
  for (const track of companyTracks) {
    await prisma.dSACompanyTrack.upsert({
      where: { slug: track.slug },
      update: track,
      create: track,
    });
  }
  console.log(`Seeded ${companyTracks.length} company tracks`);

  console.log("DSA seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
